### ISSUE TITLE
The module only create the courses and Categories locally   

### ISSUE THREAD

**Issue by abubaker-hmd** [syk1k/moodle_odoo#3]
as the title say 
it ssave the data on odoo postgre only and not throw the web service to the moodle
or is it only me ??
please reply 
Thank you

**Comment by syk1k** [comment]
Sorry this module is obselete. You can check the newest here https://github.com/syk1k/custom-addons

**Comment by syk1k** [comment]
Check the last version https://github.com/syk1k/custom-addons
